# LexChain parser benchmark — Docling vs MinerU vs Marker on OHR-Bench (Law)

**Kaggle setup:** GPU T4 x2 accelerator, internet ON.

Flow: **Cell 1** setup → **Cell 2** 3-document smoke test + full-run time estimate → *approve* → **Cell 3** full run (95 docs) → **Cell 4** metrics table + CSV.

**If the session dies:** progress is checkpointed after every document in `/kaggle/working/results`. In a new session, add the previous run's output as an *Input dataset*, then pass `--restore-from /kaggle/input/<slug>/results` in Cell 3.

In [1]:
# Cell 1 — clone repo + set up envs, data, models (~15-25 min first time)
REPO_URL = "https://github.com/MarvinPescos/lexchain-parser-bench.git"

import os
if not os.path.exists("/kaggle/working/lexchain-parser-bench"):
    !git clone {REPO_URL} /kaggle/working/lexchain-parser-bench
%cd /kaggle/working/lexchain-parser-bench
!git pull
!nvidia-smi -L
!bash setup.sh

Cloning into '/kaggle/working/lexchain-parser-bench'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 30 (delta 9), reused 29 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (30/30), 34.34 KiB | 2.86 MiB/s, done.
Resolving deltas: 100% (9/9), done.
/kaggle/working/lexchain-parser-bench
Already up to date.
GPU 0: Tesla T4 (UUID: GPU-95e78552-3d8a-7dd8-bc62-e5accb0aeb01)
GPU 1: Tesla T4 (UUID: GPU-77fda76f-90d6-3e7e-dfb4-5bd88f693f32)
== envs: /kaggle/tmp/envs | data: /kaggle/tmp/ohr_data | hf cache: /kaggle/tmp/hf
== env docling: installing docling
warning: The `--system` flag has no effect, `uv venv` always ignores virtual environments when finding a Python interpreter; did you mean `--no-managed-python`?
Using CPython 3.11.15
Creating virtual environment at: /kaggle/tmp/envs/docling
Activate with: source /kaggle/tmp/envs/docling/bin/activate
== env mineru: installing mineru[core]
warning: The `--system` flag has no effect, `uv venv` always ignores virtual environments when finding a Python interpreter; did you mean `--no-managed-python`?
Using CPython 3.11.15
Creating virtual environment at: /kaggle/tmp/envs/mineru
Activate with: source /kaggle/tmp/envs/mineru/bin/activate
== env marker: installing marker-pdf
warning: The `--system` flag has no effect, `uv venv` always ignores virtual environments when finding a Python interpreter; did you mean `--no-managed-python`?
Using CPython 3.11.15
Creating virtual environment at: /kaggle/tmp/envs/marker
Activate with: source /kaggle/tmp/envs/marker/bin/activate
== sanity checks
  docling 2.113.0 OK
  mineru 3.4.4 OK
  marker-pdf 1.10.2 OK
== eval dependencies (base python)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 27.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 68.8 MB/s eta 0:00:00
== OHR-Bench data (Law domain)
  downloading pdfs.zip ...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
pdfs.zip: 100%|█████████████████████████████| 1.52G/1.52G [00:08<00:00, 172MB/s]
  extracted 95 files -> /kaggle/tmp/ohr_data/pdfs/law
  downloading retrieval.zip ...
retrieval.zip: 100%|█████████████████████████| 126M/126M [00:03<00:00, 33.0MB/s]
  extracted 95 files -> /kaggle/tmp/ohr_data/gt/law
  law PDFs: 95, GT files: 95, matched: 95
== pre-downloading model weights (best effort; tools also download on first use)
Downloading layout model...                               ]8;id=9071366;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/docling/utils/model_downloader.py\model_downloader.py]8;;\:]8;id=9071367;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/docling/utils/model_downloader.py#68\68]8;;\
HTTP Request: GET https://huggingface.co/api/agent-harnesses     ]8;id=9071374;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071375;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
"HTTP/1.1 200 OK"
HTTP Request: GET                                                ]8;id=9071380;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071381;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/models/docling-project/docling-layout
-heron/revision/main "HTTP/1.1 200 OK"
HTTP Request: GET                                                ]8;id=9071386;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071387;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/models/docling-project/docling-layout
-heron/tree/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8?recursive=t
rue&expand=false "HTTP/1.1 200 OK"
Downloading bytes:                                         |  0.00B
Reconstructing (incomplete total...): |           |  0.00B /  0.00B

Fetching 6 files:   0%|                                  | 0/6 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0%|       |  0.00B /  172MB            HTTP Request: HEAD                                               ]8;id=9071392;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071393;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-layout-heron/reso
lve/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/preprocessor_config
.json "HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD                                               ]8;id=9071398;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071399;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/pr
eprocessor_config.json "HTTP/1.1 200 OK"
HTTP Request: GET                                                ]8;id=9071404;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071405;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/pr
eprocessor_config.json "HTTP/1.1 200 OK"

Reconstructing (incomplete total...):   0%|       |  0.00B /  172MB
Downloading bytes:                                         |   444B            HTTP Request: HEAD                                               ]8;id=9071410;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071411;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-layout-heron/reso
lve/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/config.json
"HTTP/1.1 307 Temporary Redirect"
HTTP Request: HEAD                                               ]8;id=9071416;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071417;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-layout-heron/reso
lve/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/docling_heron_400.p
ng "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Warning: You are sending unauthenticated requests to the HF Hub.    ]8;id=9071424;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/huggingface_hub/utils/_http.py\_http.py]8;;\:]8;id=9071425;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/huggingface_hub/utils/_http.py#951\951]8;;\
Please set a HF_TOKEN to enable higher rate limits and faster
downloads.
HTTP Request: HEAD                                               ]8;id=9071430;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071431;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/co
nfig.json "HTTP/1.1 200 OK"
HTTP Request: HEAD                                               ]8;id=9071436;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071437;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/do
cling_heron_400.png "HTTP/1.1 200 OK"
HTTP Request: HEAD                                               ]8;id=9071442;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071443;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-layout-heron/reso
lve/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/.gitattributes
"HTTP/1.1 307 Temporary Redirect"
HTTP Request: GET                                                ]8;id=9071448;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071449;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/co
nfig.json "HTTP/1.1 200 OK"

Reconstructing (incomplete total...):   0%|       |   444B /  172MB            HTTP Request: HEAD                                               ]8;id=9071454;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071455;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-layout-heron/reso
lve/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/README.md "HTTP/1.1
307 Temporary Redirect"
HTTP Request: HEAD                                               ]8;id=9071460;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071461;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/.g
itattributes "HTTP/1.1 200 OK"
HTTP Request: GET                                                ]8;id=9071466;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071467;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/do
cling_heron_400.png "HTTP/1.1 200 OK"

Reconstructing (incomplete total...):   0%|       | 3.71kB /  172MB            HTTP Request: HEAD                                               ]8;id=9071472;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071473;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/RE
ADME.md "HTTP/1.1 200 OK"
HTTP Request: GET                                                ]8;id=9071478;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071479;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/.g
itattributes "HTTP/1.1 200 OK"

Reconstructing (incomplete total...):   0%|       |  101kB /  172MB

Fetching 6 files:  17%|████▎                     | 1/6 [00:00<00:01,  4.89it/s]HTTP Request: GET                                                ]8;id=9071484;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071485;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-layout-heron/8f39ad3c0b4c58e9c2d2c84a38465abf757272d8/RE
ADME.md "HTTP/1.1 200 OK"

Reconstructing (incomplete total...):   0%|       |  102kB /  172MB
Downloading bytes: ██████████████████████████▍             |  113MB,  151MB/s
Downloading bytes: ██████████████████████████████████▋     |  149MB,  222MB/s
Reconstructing (incomplete total...): 100%|███████|  172MB /  172MB, 70.3MB/s

Fetching 6 files: 100%|██████████████████████████| 6/6 [00:01<00:00,  4.55it/s]
Download complete: : ██████████████████████████████████████|  162MB,  258MB/s
Reconstruction complete: 100%|████████████████████|  172MB /  172MB,  174MB/s  Downloading tableformer model...                          ]8;id=9071491;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/docling/utils/model_downloader.py\model_downloader.py]8;;\:]8;id=9071492;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/docling/utils/model_downloader.py#76\76]8;;\
HTTP Request: GET                                                ]8;id=9071497;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071498;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/models/docling-project/docling-models
/revision/v2.3.0 "HTTP/1.1 200 OK"
HTTP Request: GET                                                ]8;id=9071503;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071504;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/models/docling-project/docling-models
/tree/fc0f2d45e2218ea24bce5045f58a389aed16dc23?recursive=true&ex
pand=false "HTTP/1.1 200 OK"


Downloading bytes:                                         |  0.00B


Reconstructing (incomplete total...): |           |  0.00B /  0.00B



Fetching 8 files:   0%|                                  | 0/8 [00:00<?, ?it/s]


Reconstructing (incomplete total...):   0%|       |  0.00B /  145MB


Reconstructing (incomplete total...):   0%|       |  0.00B /  358MB            HTTP Request: HEAD                                               ]8;id=9071509;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071510;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-models/resolve/fc
0f2d45e2218ea24bce5045f58a389aed16dc23/README.md "HTTP/1.1 307
Temporary Redirect"
HTTP Request: HEAD                                               ]8;id=9071515;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071516;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-models/resolve/fc
0f2d45e2218ea24bce5045f58a389aed16dc23/config.json "HTTP/1.1 307
Temporary Redirect"
HTTP Request: HEAD                                               ]8;id=9071521;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071522;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-models/resolve/fc
0f2d45e2218ea24bce5045f58a389aed16dc23/model_artifacts/tableform
er/fast/tm_config.json "HTTP/1.1 307 Temporary Redirect"
Download complete: : ██████████████████████████████████████|  162MB,  258MB/s
Reconstruction complete: 100%|████████████████████|  172MB /  172MB,  174MB/s
HTTP Request: HEAD                                               ]8;id=9071527;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071528;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-models/fc0f2d45e2218ea24bce5045f58a389aed16dc23/config.j
son "HTTP/1.1 200 OK"
HTTP Request: HEAD                                               ]8;id=9071533;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071534;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-models/fc0f2d45e2218ea24bce5045f58a389aed16dc23/README.m
d "HTTP/1.1 200 OK"
HTTP Request: HEAD                                               ]8;id=9071539;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071540;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-models/fc0f2d45e2218ea24bce5045f58a389aed16dc23/model_ar
tifacts%2Ftableformer%2Ffast%2Ftm_config.json "HTTP/1.1 200 OK"
HTTP Request: GET                                                ]8;id=9071545;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071546;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-models/fc0f2d45e2218ea24bce5045f58a389aed16dc23/config.j
son "HTTP/1.1 200 OK"



Reconstructing (incomplete total...):   0%|       |  0.00B /  358MB


Reconstructing (incomplete total...):   0%|       |  41.0B /  358MB

Downloading bytes:                                         |  41.0B            HTTP Request: GET                                                ]8;id=9071551;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071552;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-models/fc0f2d45e2218ea24bce5045f58a389aed16dc23/README.m
d "HTTP/1.1 200 OK"



Reconstructing (incomplete total...):   0%|       |  41.0B /  358MB            HTTP Request: HEAD                                               ]8;id=9071557;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071558;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/docling-project/docling-models/resolve/fc
0f2d45e2218ea24bce5045f58a389aed16dc23/.gitattributes "HTTP/1.1
307 Temporary Redirect"
HTTP Request: GET                                                ]8;id=9071563;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071564;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-models/fc0f2d45e2218ea24bce5045f58a389aed16dc23/model_ar
tifacts%2Ftableformer%2Ffast%2Ftm_config.json "HTTP/1.1 200 OK"



Reconstructing (incomplete total...):   0%|       | 3.45kB /  358MB            HTTP Request: HEAD                                               ]8;id=9071569;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071570;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\
https://huggingface.co/api/resolve-cache/models/docling-project/
docling-models/fc0f2d45e2218ea24bce5045f58a389aed16dc23/.gitattr
ibutes "HTTP/1.1 200 OK"
HTTP Request: GET                                                ]8;id=9071575;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py\_client.py]8;;\:]8;id=9071576;file:///kaggle/tmp/envs/docling/lib/python3.11/site-packages/httpx/_client.py#1025\1025]8;;\

In [2]:
# Cell 2 — smoke test: 3 smallest PDFs through all 3 tools, then estimate the full run
!python run_benchmark.py --limit 3
!python evaluate.py
!python estimate_runtime.py

[bench 19:41:04] condition: digital (pdfs: /kaggle/tmp/ohr_data/pdfs/law, results: /kaggle/working/results)
[bench 19:41:04] 3 docs x 3 tools
[bench 19:41:04] GPUs detected: ['0', '1'] -> 2 parallel worker(s)
[bench 19:41:04] docling: worker started on GPU 0 (3 docs pending, restart 0)
[bench 19:41:04] mineru: worker started on GPU 1 (3 docs pending, restart 0)
[bench 19:41:34] docling: all docs processed
[bench 19:41:34] marker: worker started on GPU 0 (3 docs pending, restart 0)
[bench 19:41:39] mineru: all docs processed
[bench 19:42:04] marker: all docs processed
[bench 19:42:04] done in 1.0 min
[bench 19:42:04] docling: {'success': 3}
[bench 19:42:04] mineru: {'success': 3}
[bench 19:42:04] marker: {'success': 3}
Ground truth: 95 docs, 1187 pages
[docling] 3 docs, success 100%, NED 0.1816
[mineru] 3 docs, success 100%, NED 0.2430
[marker] 3 docs, success 100%, NED 0.1587

| Tool    |   NED ↓ |   CER ↓ |   TEDS ↑ |   TEDS-S ↑ |   Read. order ↓ |   s/page ↓ |   Success ↑ |
|:--------|--------:|--------:|---------:|-----------:|----------------:|-----------:|------------:|
| docling |  0.1816 |  0.2040 |   0.5958 |     0.8788 |          0.0267 |     0.4114 |      1.0000 |
| mineru  |  0.2430 |  0.2863 |   0.5941 |     0.8788 |          0.0741 |     2.7038 |      1.0000 |
| marker  |  0.1587 |  0.1796 |   0.5941 |     0.8788 |          0.0494 |     1.2884 |      1.0000 |

Wrote /kaggle/working/results/results_per_doc.csv, results_summary.csv, results.md
Note: quality metrics are computed over successful docs only; TEDS covers docs whose GT contains tables (see gt_tables_scored).
=== Full-run estimate: 1187 pages, 95 docs ===
docling: 0.4 s/page over 3 doc(s) (model load 21s) -> ~0.1 h alone
mineru: 2.7 s/page over 3 doc(s) (model load 7s) -> ~0.9 h alone
marker: 1.3 s/page over 3 doc(s) (model load 13s) -> ~0.4 h alone

Projected wall time on 2 GPUs: ~0.9 h
Kaggle GPU sessions cap at ~12 h. If the estimate exceeds that, run in chunks -- every document is checkpointed; rerunning the run cell resumes.

**STOP — review the estimate above before running the full benchmark.**

Resuming a previous session? Attach its output as an input dataset and use:
`!python run_benchmark.py --restore-from /kaggle/input/<slug>/results`

In [3]:
# Cell 3 — full run (resumable; smoke-test docs are skipped automatically)
!python run_benchmark.py

[bench 19:42:06] condition: digital (pdfs: /kaggle/tmp/ohr_data/pdfs/law, results: /kaggle/working/results)
[bench 19:42:06] 95 docs x 3 tools
[bench 19:42:06] GPUs detected: ['0', '1'] -> 2 parallel worker(s)
[bench 19:42:06] docling: worker started on GPU 0 (92 docs pending, restart 0)
[bench 19:42:06] mineru: worker started on GPU 1 (92 docs pending, restart 0)
[bench 19:54:51] docling: all docs processed
[bench 19:54:51] marker: worker started on GPU 0 (92 docs pending, restart 0)
[bench 19:56:26] mineru: all docs processed
[bench 21:00:26] marker: all docs processed
[bench 21:00:26] done in 78.3 min
[bench 21:00:26] docling: {'success': 95}
[bench 21:00:26] mineru: {'success': 95}
[bench 21:00:26] marker: {'success': 95}

In [4]:
# Cell 4 — evaluate + paper table (CSV + markdown saved to /kaggle/working/results)
!python evaluate.py

import pandas as pd
from IPython.display import display
display(pd.read_csv("/kaggle/working/results/results_summary.csv"))
print(open("/kaggle/working/results/results.md").read())

Ground truth: 95 docs, 1187 pages
[docling] 95 docs, success 100%, NED 0.1582
[mineru] 95 docs, success 100%, NED 0.1435
[marker] 95 docs, success 100%, NED 0.1195

| Tool    |   NED ↓ |   CER ↓ |   TEDS ↑ |   TEDS-S ↑ |   Read. order ↓ |   s/page ↓ |   Success ↑ |
|:--------|--------:|--------:|---------:|-----------:|----------------:|-----------:|------------:|
| docling |  0.1582 |  0.2157 |   0.3886 |     0.4535 |          0.0429 |     0.6353 |      1.0000 |
| mineru  |  0.1435 |  0.2104 |   0.3221 |     0.3815 |          0.0342 |     0.7366 |      1.0000 |
| marker  |  0.1195 |  0.1935 |   0.4640 |     0.5390 |          0.0236 |     3.3109 |      1.0000 |

Wrote /kaggle/working/results/results_per_doc.csv, results_summary.csv, results.md
Note: quality metrics are computed over successful docs only; TEDS covers docs whose GT contains tables (see gt_tables_scored).

,tool,docs,success_rate,ned,cer,teds,teds_s,gt_tables_scored,reading_order,s_per_page,failures
0,docling,95,1.0,0.158209,0.215748,0.388619,0.453527,127,0.042887,0.635338,0
1,mineru,95,1.0,0.143550,0.210358,0.322092,0.381503,127,0.034225,0.736602,0
2,marker,95,1.0,0.119534,0.193495,0.464002,0.538974,127,0.023551,3.310901,0

| Tool    |   NED ↓ |   CER ↓ |   TEDS ↑ |   TEDS-S ↑ |   Read. order ↓ |   s/page ↓ |   Success ↑ |
|:--------|--------:|--------:|---------:|-----------:|----------------:|-----------:|------------:|
| docling |  0.1582 |  0.2157 |   0.3886 |     0.4535 |          0.0429 |     0.6353 |      1.0000 |
| mineru  |  0.1435 |  0.2104 |   0.3221 |     0.3815 |          0.0342 |     0.7366 |      1.0000 |
| marker  |  0.1195 |  0.1935 |   0.4640 |     0.5390 |          0.0236 |     3.3109 |      1.0000 |

---
## Part 2 — Simulated-scanned condition

The Law set is 88 digital-born / 7 natively-scanned PDFs, but LexChain's real workload is mostly scanned. The cells below rasterize **all 95 PDFs at 200 DPI into image-only PDFs** (no text layer, identical filenames → ground truth maps 1:1) and rerun the benchmark with every tool forced through its **OCR path**. Tool configs are identical to Part 1 — the input condition is the only variable.

Results go to `/kaggle/working/results_scanned` (Part 1 results are untouched). Same checkpoint/resume behavior; to resume a dead session: `--restore-from /kaggle/input/<slug>/results_scanned`.

In [5]:
import subprocess
src = subprocess.run(["find","/kaggle/input","-type","d","-name","results"],capture_output=True,text=True).stdout.strip().split("\n")[0]
!cp -r {src} /kaggle/working/
!ls /kaggle/working/results/docling/meta | wc -l   # expect 95

95

In [6]:
# Cell 5 — build the simulated-scanned set (resumable; ~10-20 min, CPU only)
!python make_scanned.py

  ACCELERATEDTECHNOLOGIESHOLDINGCORP_04_24_2003-EX-10.13-JOINT VENTURE AGREEMENT.pdf: 3 pages rasterized @ 200 DPI
  ADMA BioManufacturing, LLC -  Amendment #3 to Manufacturing Agreement .pdf: 6 pages rasterized @ 200 DPI
  ADUROBIOTECH,INC_06_02_2020-EX-10.7-CONSULTING AGREEMENT.pdf: 4 pages rasterized @ 200 DPI
  AIRTECHINTERNATIONALGROUPINC_05_08_2000-EX-10.4-FRANCHISE AGREEMENT.pdf: 16 pages rasterized @ 200 DPI
  AMERICASSHOPPINGMALLINC_12_10_1999-EX-10.2-SITE DEVELOPMENT AND HOSTING AGREEMENT.pdf: 5 pages rasterized @ 200 DPI
  ASIANDRAGONGROUPINC_08_11_2005-EX-10.5-Reseller Agreement.pdf: 18 pages rasterized @ 200 DPI
  ArcGroupInc_20171211_8-K_EX-10.1_10976103_EX-10.1_Sponsorship Agreement.pdf: 4 pages rasterized @ 200 DPI
  ArmstrongFlooringInc_20190107_8-K_EX-10.2_11471795_EX-10.2_Intellectual Property Agreement.pdf: 40 pages rasterized @ 200 DPI
  Array BioPharma Inc. - LICENSE, DEVELOPMENT AND COMMERCIALIZATION AGREEMENT.pdf: 107 pages rasterized @ 200 DPI
  BANUESTRAFINANCIALCORP_09_08_2006-EX-10.16-AGENCY AGREEMENT.pdf: 14 pages rasterized @ 200 DPI
  BIOAMBERINC_04_10_2013-EX-10.34-DEVELOPMENT AGREEMENT (1).pdf: 18 pages rasterized @ 200 DPI
  CHERRYHILLMORTGAGEINVESTMENTCORP_09_26_2013-EX-10.1-Strategic Alliance Agreement.pdf: 11 pages rasterized @ 200 DPI
  CYBERIANOUTPOSTINC_07_09_1998-EX-10.13-PROMOTION AGREEMENT.pdf: 5 pages rasterized @ 200 DPI
  CardlyticsInc_20180112_S-1_EX-10.16_11002987_EX-10.16_Maintenance Agreement1.pdf: 47 pages rasterized @ 200 DPI
  CcRealEstateIncomeFundadv_20181205_POS 8C_EX-99.(H)(3)_11447739_EX-99.(H)(3)_Marketing Agreement.pdf: 14 pages rasterized @ 200 DPI
  CnsPharmaceuticalsInc_20200326_8-K_EX-10.1_12079626_EX-10.1_Development Agreement.pdf: 5 pages rasterized @ 200 DPI
  DIVERSINETCORP_03_01_2012-EX-4-RESELLER AGREEMENT.pdf: 15 pages rasterized @ 200 DPI
  DUDE_05c32b8ef101e6b827ccc12b72fddd11.pdf: 18 pages rasterized @ 200 DPI
  DUDE_0df057296a2a8ad25780078b0b75d8df.pdf: 2 pages rasterized @ 200 DPI
  DUDE_0ed48a776cbea208d38426da6a01ead6.pdf: 5 pages rasterized @ 200 DPI
  DUDE_0f649220ea1397b3f4d0fb272b4427d2.pdf: 7 pages rasterized @ 200 DPI
  DUDE_0fd01e9cac08043b447c0a0477160308.pdf: 4 pages rasterized @ 200 DPI
  DUDE_10b37e7fb16a67ac2ca19e47b27c8d3d.pdf: 14 pages rasterized @ 200 DPI
  DUDE_128ea53b9421b04ccae7a482c0d3bbda.pdf: 10 pages rasterized @ 200 DPI
  DUDE_1a1e3c10c247e83b96f00fe8b926b844.pdf: 6 pages rasterized @ 200 DPI
  DUDE_1b0b3fb5ec538aa8ca1da27c3b500f36.pdf: 1 pages rasterized @ 200 DPI
  DUDE_2306300e8316977d3c9fd29489d1c188.pdf: 3 pages rasterized @ 200 DPI
  DUDE_23e1a6a3ab002ce5e17718e5c2309110.pdf: 16 pages rasterized @ 200 DPI
  DUDE_25ab1502f316011a4971ea47888bf6c4.pdf: 4 pages rasterized @ 200 DPI
  DUDE_26cc8b443ff3ed96cb93f2da89441c33.pdf: 3 pages rasterized @ 200 DPI
  DUDE_2b2129b334e2acd2a4dce3238419819f.pdf: 6 pages rasterized @ 200 DPI
  DUDE_39dff27605b4806c75e7ae30609a05d0.pdf: 8 pages rasterized @ 200 DPI
  DUDE_3c0c04e9af041ec0835ab4899a827cd0.pdf: 20 pages rasterized @ 200 DPI
  DUDE_3cc88affca79359d0a2307fcb6308f95.pdf: 14 pages rasterized @ 200 DPI
  DUDE_4bbae386431f60e15100691032a61886.pdf: 3 pages rasterized @ 200 DPI
  DUDE_5338a15055d43ed03d2bf41dfe0e4da0.pdf: 2 pages rasterized @ 200 DPI
  DUDE_55e351401d03315e5e70299499e2c83e.pdf: 5 pages rasterized @ 200 DPI
  DUDE_6cd4b999973e3787ac703d4417881ad2.pdf: 1 pages rasterized @ 200 DPI
  DUDE_7c3f6204b3241f142f0f8eb8e1fefe7a.pdf: 15 pages rasterized @ 200 DPI
  DUDE_7d5f6660f892400387fb8d91cfad4592.pdf: 3 pages rasterized @ 200 DPI
  DUDE_83a7960c76b6ec0c76cdf93d8fe7c715.pdf: 20 pages rasterized @ 200 DPI
  DUDE_8c8f5a5a1488c3aa27dafb5d5a7b1f56.pdf: 3 pages rasterized @ 200 DPI
  DUDE_9666ea671ff69db9b320d447959e2195.pdf: 7 pages rasterized @ 200 DPI
  DUDE_9739045cbfd4c77922f844295ab3a302.pdf: 6 pages rasterized @ 200 DPI
  DUDE_9bd004110e42eab4c5dfbef2a93b9f2a.pdf: 5 pages rasterized @ 200 DPI
  DUDE_a2ed58df070a5430f90bab8ee2c90ced.pdf: 2 pages rasterized @ 200 DPI
  DUDE_b05a7904ab29fe72d55491485c0ca71d.pdf: 17 pages rasterized @ 200 DPI
  DUDE_b223a91eb485ffff0cb9b39d71774b16.pdf: 2 pages rasterized @ 200 DPI
  DUDE_b62dc913e04e2bbea95d608f9943868b.pdf: 18 pages rasterized @ 200 DPI
  DUDE_bcdf261dab03a8755acb5b795b4912cc.pdf: 2 pages rasterized @ 200 DPI
  DUDE_dd814385b004d770a820cf236db667ff.pdf: 11 pages rasterized @ 200 DPI
  DUDE_f4ae53cfb28429bf8508dc90d812c458.pdf: 6 pages rasterized @ 200 DPI
  DYNTEKINC_07_30_1999-EX-10-ONLINE HOSTING AGREEMENT.pdf: 6 pages rasterized @ 200 DPI
  ENERGYXXILTD_05_08_2015-EX-10.13-Transportation AGREEMENT.pdf: 25 pages rasterized @ 200 DPI
  EcoScienceSolutionsInc_20171117_8-K_EX-10.1_10956472_EX-10.1_Endorsement Agreement.pdf: 7 pages rasterized @ 200 DPI
  FEDERATEDGOVERNMENTINCOMESECURITIESINC_04_28_2020-EX-99.SERV AGREE-SERVICES AGREEMENT_SECONDAMENDMENT.pdf: 1 pages rasterized @ 200 DPI
  FIBROGENINC_10_01_2014-EX-10.11-COLLABORATION AGREEMENT.pdf: 53 pages rasterized @ 200 DPI
  FIDELITYNATIONALINFORMATIONSERVICES,INC_08_05_2009-EX-10.3-INTELLECTUAL PROPERTY AGREEMENT.pdf: 31 pages rasterized @ 200 DPI
  GRIDIRONBIONUTRIENTS,INC_02_05_2020-EX-10.3-SUPPLY AGREEMENT.pdf: 3 pages rasterized @ 200 DPI
  GULFSOUTHMEDICALSUPPLYINC_12_24_1997-EX-4-AFFILIATE AGREEMENT.pdf: 8 pages rasterized @ 200 DPI
  GWG HOLDINGS, INC. - ORDERLY MARKETING AGREEMENT.pdf: 17 pages rasterized @ 200 DPI
  HALITRON,INC_03_01_2005-EX-10.15-SPONSORSHIP AND DEVELOPMENT AGREEMENT.pdf: 6 pages rasterized @ 200 DPI
  HealthcareIntegratedTechnologiesInc_20190812_8-K_EX-10.1_11776966_EX-10.1_Reseller Agreement.pdf: 5 pages rasterized @ 200 DPI
  IDREAMSKYTECHNOLOGYLTD_07_03_2014-EX-10.39-Cooperation Agreement on Mobile Game Business.pdf: 29 pages rasterized @ 200 DPI
  IntegrityFunds_20200121_485BPOS_EX-99.E UNDR CONTR_11948727_EX-99.E UNDR CONTR_Service Agreement.pdf: 8 pages rasterized @ 200 DPI
  KNOWLABS,INC_08_15_2005-EX-10-INTELLECTUAL PROPERTY AGREEMENT.pdf: 3 pages rasterized @ 200 DPI
  KitovPharmaLtd_20190326_20-F_EX-4.15_11584449_EX-4.15_Manufacturing Agreement.pdf: 19 pages rasterized @ 200 DPI
  MACY_S,INC_05_11_2020-EX-99.4-JOINT FILING AGREEMENT.pdf: 1 pages rasterized @ 200 DPI
  MARSHALLHOLDINGSINTERNATIONAL,INC_04_14_2004-EX-10.15-ENDORSEMENT AGREEMENT.pdf: 3 pages rasterized @ 200 DPI
  MPLXLP_06_17_2015-EX-10.1-TRANSPORTATION SERVICES AGREEMENT.pdf: 26 pages rasterized @ 200 DPI
  MRSFIELDSORIGINALCOOKIESINC_01_29_1998-EX-10-FRANCHISE AGREEMENT.pdf: 45 pages rasterized @ 200 DPI
  N2KINC_10_16_1997-EX-10.16-SPONSORSHIP AGREEMENT.pdf: 10 pages rasterized @ 200 DPI
  NETGEAR,INC_04_21_2003-EX-10.16-AMENDMENT TO THE DISTRIBUTOR AGREEMENT BETWEEN INGRAM MICRO AND NETGEAR-.pdf: 2 pages rasterized @ 200 DPI
  NEXSTARFINANCEHOLDINGSINC_03_27_2002-EX-10.26-OUTSOURCING AGREEMENT.pdf: 23 pages rasterized @ 200 DPI
  OLDAPIWIND-DOWNLTD_01_08_2016-EX-1.3-AGENCY AGREEMENT2.pdf: 3 pages rasterized @ 200 DPI
  OPTIMIZEDTRANSPORTATIONMANAGEMENT,INC_07_26_2000-EX-6.6-DISTRIBUTOR AGREEMENT.pdf: 3 pages rasterized @ 200 DPI
  ParatekPharmaceuticalsInc_20170505_10-KA_EX-10.29_10323872_EX-10.29_Outsourcing Agreement.pdf: 49 pages rasterized @ 200 DPI
  PareteumCorp_20081001_8-K_EX-99.1_2654808_EX-99.1_Hosting Agreement.pdf: 30 pages rasterized @ 200 DPI
  PlayboyEnterprisesInc_20090220_10-QA_EX-10.2_4091580_EX-10.2_Content License Agreement_ Marketing Agreement_ Sales-Purchase Agreement2.pdf: 2 pages rasterized @ 200 DPI
  RISEEDUCATIONCAYMANLTD_04_17_2020-EX-4.23-SERVICE AGREEMENT.pdf: 9 pages rasterized @ 200 DPI
  ReynoldsConsumerProductsInc_20191115_S-1_EX-10.18_11896469_EX-10.18_Supply Agreement.pdf: 16 pages rasterized @ 200 DPI
  RgcResourcesInc_20151216_8-K_EX-10.3_9372751_EX-10.3_Franchise Agreement.pdf: 3 pages rasterized @ 200 DPI
  SEPARATEACCOUNTIIOFAGL_05_02_2011-EX-99.(J)(4)-UNCONDITIONAL CAPITAL MAINTENANCE AGREEMENT.pdf: 4 pages rasterized @ 200 DPI
  SIBANNAC,INC_12_04_2017-EX-2.1-Strategic Alliance Agreement.pdf: 5 pages rasterized @ 200 DPI
  ScansourceInc_20190822_10-K_EX-10.38_11793958_EX-10.38_Distributor Agreement2.pdf: 3 pages rasterized @ 200 DPI
  TRICITYBANKSHARESCORP_05_15_1998-EX-10-OUTSOURCING AGREEMENT.pdf: 21 pages rasterized @ 200 DPI
  TheglobeComInc_19990503_S-1A_EX-10.20_5416126_EX-10.20_Co-Branding Agreement.pdf: 9 pages rasterized @ 200 DPI
  UnionDentalHoldingsInc_20050204_8-KA_EX-10_3345577_EX-10_Affiliate Agreement.pdf: 3 pages rasterized @ 200 DPI
  VAXCYTE,INC_05_22_2020-EX-10.19-SUPPLY AGREEMENT.pdf: 34 pages rasterized @ 200 DPI
  VIVINT SOLAR, INC. - NON-COMPETITION AGREEMENT.pdf: 4 pages rasterized @ 200 DPI
  VnueInc_20150914_8-K_EX-10.1_9259571_EX-10.1_Promotion Agreement.pdf: 3 pages rasterized @ 200 DPI
  WHITESMOKE,INC_11_08_2011-EX-10.26-PROMOTION AND DISTRIBUTION AGREEMENT.pdf: 40 pages rasterized @ 200 DPI
  WOMENSGOLFUNLIMITEDINC_03_29_2000-EX-10.13-ENDORSEMENT AGREEMENT.pdf: 7 pages rasterized @ 200 DPI
  XACCT Technologies, Inc.SUPPORT AND MAINTENANCE AGREEMENT.pdf: 3 pages rasterized @ 200 DPI
  ZtoExpressCaymanInc_20160930_F-1_EX-10.10_9752871_EX-10.10_Transportation Agreement.pdf: 4 pages rasterized @ 200 DPI

Verifying outputs are image-only ...

95 converted, 0 skipped (already done), 0 failed, 0 failed verification
95/95 scanned PDFs ready in /kaggle/tmp/ohr_data/pdfs/law_scanned (429 MB)

In [7]:
# Cell 6 — scanned-condition smoke test (3 docs) + full-run estimate
# OCR mode is typically 3-6x slower than the digital condition — check the
# projection against Kaggle's ~12 h session cap before running Cell 7.
!python run_benchmark.py --condition scanned --limit 3
!python estimate_runtime.py --results-dir /kaggle/working/results_scanned --label scanned

[bench 21:07:31] condition: scanned (pdfs: /kaggle/tmp/ohr_data/pdfs/law_scanned, results: /kaggle/working/results_scanned)
[bench 21:07:31] 3 docs x 3 tools
[bench 21:07:31] GPUs detected: ['0', '1'] -> 2 parallel worker(s)
[bench 21:07:31] docling: worker started on GPU 0 (3 docs pending, restart 0)
[bench 21:07:31] mineru: worker started on GPU 1 (3 docs pending, restart 0)
[bench 21:08:01] docling: all docs processed
[bench 21:08:01] mineru: all docs processed
[bench 21:08:01] marker: worker started on GPU 0 (3 docs pending, restart 0)
[bench 21:09:46] marker: all docs processed
[bench 21:09:46] done in 2.3 min
[bench 21:09:46] docling: {'success': 3}
[bench 21:09:46] mineru: {'success': 3}
[bench 21:09:46] marker: {'success': 3}
=== Full-run estimate [scanned]: 1187 pages, 95 docs ===
docling: 2.5 s/page over 3 doc(s) (model load 12s) -> ~0.8 h alone
mineru: 3.8 s/page over 3 doc(s) (model load 4s) -> ~1.2 h alone
marker: 17.8 s/page over 3 doc(s) (model load 13s) -> ~5.9 h alone

Projected wall time on 2 GPUs: ~5.9 h
Kaggle GPU sessions cap at ~12 h. If the estimate exceeds that, run in chunks -- every document is checkpointed; rerunning the run cell resumes.

**STOP — review the scanned-condition estimate above before the full OCR run.** If it exceeds the session cap, run Cell 7 in chunks across sessions (checkpointed, resumable via `--restore-from`).

In [8]:
# Cell 7 — full scanned-condition run (resumable; smoke docs skipped)
!python run_benchmark.py --condition scanned

[bench 21:09:46] condition: scanned (pdfs: /kaggle/tmp/ohr_data/pdfs/law_scanned, results: /kaggle/working/results_scanned)
[bench 21:09:46] 95 docs x 3 tools
[bench 21:09:46] GPUs detected: ['0', '1'] -> 2 parallel worker(s)
[bench 21:09:46] docling: worker started on GPU 0 (92 docs pending, restart 0)
[bench 21:09:46] mineru: worker started on GPU 1 (92 docs pending, restart 0)
[bench 21:30:01] mineru: all docs processed
[bench 21:30:01] marker: worker started on GPU 1 (92 docs pending, restart 0)
[bench 21:58:37] docling: all docs processed
[bench 03:25:38] marker: all docs processed
[bench 03:25:38] done in 375.9 min
[bench 03:25:38] docling: {'success': 95}
[bench 03:25:38] mineru: {'success': 95}
[bench 03:25:38] marker: {'success': 95}

In [9]:
# Cell 8 — combined evaluation: digital-born (88) vs natively-scanned (7) vs
# simulated-scanned (95), per tool, + ranking-stability check
!python evaluate.py --detect-scanned
!python compare_conditions.py

import pandas as pd
from IPython.display import display
display(pd.read_csv("/kaggle/working/results/comparison.csv"))
print(open("/kaggle/working/results/comparison.md").read())

detect-scanned: 88 digital-born, 7 natively scanned -> /kaggle/working/results/digital_docs.txt, scanned_docs.txt

--- digital-born (n=88, /kaggle/working/results) ---
[docling] 87 docs, success 100%, NED 0.1512
[mineru] 87 docs, success 100%, NED 0.1400
[marker] 87 docs, success 100%, NED 0.1159

--- natively-scanned (n=7, /kaggle/working/results) ---
[docling] 7 docs, success 100%, NED 0.2583
[mineru] 7 docs, success 100%, NED 0.1969
[marker] 7 docs, success 100%, NED 0.1560

--- simulated-scanned (n=95, /kaggle/working/results_scanned) ---
[docling] 95 docs, success 100%, NED 0.2609
[mineru] 95 docs, success 100%, NED 0.1473
[marker] 95 docs, success 100%, NED 0.1124

| Condition         |   n | Tool    |   NED ↓ |   CER ↓ |   TEDS ↑ |   TEDS-S ↑ |   Read. order ↓ |   s/page ↓ |   Success ↑ |
|:------------------|----:|:--------|--------:|--------:|---------:|-----------:|----------------:|-----------:|------------:|
| digital-born      |  87 | docling |  0.1512 |  0.2130 |   0.3819 |     0.4462 |          0.0359 |     0.5895 |      1.0000 |
| digital-born      |  87 | mineru  |  0.1400 |  0.2044 |   0.3138 |     0.3695 |          0.0368 |     0.7292 |      1.0000 |
| digital-born      |  87 | marker  |  0.1159 |  0.1907 |   0.4531 |     0.5281 |          0.0252 |     2.3580 |      1.0000 |
| natively-scanned  |   7 | docling |  0.2583 |  0.2702 |   0.4673 |     0.5398 |          0.1362 |     2.3814 |      1.0000 |
| natively-scanned  |   7 | mineru  |  0.1969 |  0.3006 |   0.4186 |     0.5220 |          0.0024 |     1.1141 |      1.0000 |
| natively-scanned  |   7 | marker  |  0.1560 |  0.2265 |   0.5919 |     0.6666 |          0.0070 |    34.7448 |      1.0000 |
| simulated-scanned |  95 | docling |  0.2609 |  0.3056 |   0.3545 |     0.4238 |          0.0748 |     2.4640 |      1.0000 |
| simulated-scanned |  95 | mineru  |  0.1473 |  0.2190 |   0.3172 |     0.3807 |          0.0389 |     1.0301 |      1.0000 |
| simulated-scanned |  95 | marker  |  0.1124 |  0.1823 |   0.4635 |     0.5292 |          0.0238 |    18.0375 |      1.0000 |

## Ranking stability across conditions

- ned: ranking consistent (marker > mineru > docling)
- teds: ranking consistent (marker > docling > mineru)
- **s_per_page: ranking DIFFERS between conditions**
    - digital-born: docling > mineru > marker
    - natively-scanned: mineru > docling > marker
    - simulated-scanned: mineru > docling > marker

Wrote /kaggle/working/results/comparison.csv and comparison.md

,condition,tool,docs,success_rate,ned,cer,teds,teds_s,gt_tables_scored,reading_order,s_per_page,failures
0,digital-born,docling,87,1.0,0.151237,0.213002,0.381896,0.446153,117,0.035873,0.589465,0
1,digital-born,mineru,87,1.0,0.139994,0.204419,0.313841,0.369491,117,0.036763,0.729172,0
2,digital-born,marker,87,1.0,0.115930,0.190663,0.453070,0.528069,117,0.025150,2.358013,0
3,natively-scanned,docling,7,1.0,0.258306,0.270184,0.467282,0.539801,10,0.136178,2.381389,0
4,natively-scanned,mineru,7,1.0,0.196930,0.300603,0.418632,0.522049,10,0.002381,1.114139,0
5,natively-scanned,marker,7,1.0,0.155997,0.226477,0.591906,0.666555,10,0.007034,34.744778,0
6,simulated-scanned,docling,95,1.0,0.260856,0.305621,0.354479,0.423783,127,0.074761,2.463981,0
7,simulated-scanned,mineru,95,1.0,0.147338,0.218956,0.317217,0.380749,127,0.038877,1.030120,0
8,simulated-scanned,marker,95,1.0,0.112352,0.182288,0.463534,0.529235,127,0.023751,18.037488,0

| Condition         |   n | Tool    |   NED ↓ |   CER ↓ |   TEDS ↑ |   TEDS-S ↑ |   Read. order ↓ |   s/page ↓ |   Success ↑ |
|:------------------|----:|:--------|--------:|--------:|---------:|-----------:|----------------:|-----------:|------------:|
| digital-born      |  87 | docling |  0.1512 |  0.2130 |   0.3819 |     0.4462 |          0.0359 |     0.5895 |      1.0000 |
| digital-born      |  87 | mineru  |  0.1400 |  0.2044 |   0.3138 |     0.3695 |          0.0368 |     0.7292 |      1.0000 |
| digital-born      |  87 | marker  |  0.1159 |  0.1907 |   0.4531 |     0.5281 |          0.0252 |     2.3580 |      1.0000 |
| natively-scanned  |   7 | docling |  0.2583 |  0.2702 |   0.4673 |     0.5398 |          0.1362 |     2.3814 |      1.0000 |
| natively-scanned  |   7 | mineru  |  0.1969 |  0.3006 |   0.4186 |     0.5220 |          0.0024 |     1.1141 |      1.0000 |
| natively-scanned  |   7 | marker  |  0.1560 |  0.2265 |   0.5919 |     0.6666 |          0.0070 |    34.7448 |      1.0000 |
| simulated-scanned |  95 | docling |  0.2609 |  0.3056 |   0.3545 |     0.4238 |          0.0748 |     2.4640 |      1.0000 |
| simulated-scanned |  95 | mineru  |  0.1473 |  0.2190 |   0.3172 |     0.3807 |          0.0389 |     1.0301 |      1.0000 |
| simulated-scanned |  95 | marker  |  0.1124 |  0.1823 |   0.4635 |     0.5292 |          0.0238 |    18.0375 |      1.0000 |

## Ranking stability across conditions

- ned: ranking consistent (marker > mineru > docling)
- teds: ranking consistent (marker > docling > mineru)
- **s_per_page: ranking DIFFERS between conditions**
    - digital-born: docling > mineru > marker
    - natively-scanned: mineru > docling > marker
    - simulated-scanned: mineru > docling > marker

In [10]:
import subprocess
src = subprocess.run(["find","/kaggle/input","-type","d","-name","results"],capture_output=True,text=True).stdout.strip().split("\n")[0]
!cp -r {src} /kaggle/working/
!find /kaggle/working/results -name "*.json" | wc -l
!ls /kaggle/working/results/docling/meta | wc -l   # expect 95

579
95